### ISSUE TITLE
Easier installation idea

### ISSUE THREAD

**Issue by testman42** [Phrohdoh/oramod-ra2#83]
How hard would it be to implement extractor that opens dialog that says "direct me to your Red Alert 2 directory", and then it automatically extracts needed .mix files for this mod to work?

**Comment by GrayHatter** [comment]
`cp -r ./* /path/to/open/ra` like that?

**Comment by Phrohdoh** [comment]
It would be a matter of subclassing the installation logic, but also implementing a file browser dialog, which is not simple to do correctly.

For now do it manually.

This can remain open until and installer is made.

**Comment by abcdefg30** [comment]
I think you mean sth like a script where you enter the path to the directory of an *installed version* of ra2?

___________________________
Anyway for extraction from CD(s):
The actual problem is that the OpenRA content installer is not able to handle the CAB format. (The ra2 mixes are located in `Game1.CAB` on the CD.)
So we're waiting on OpenRA/OpenRA#8170 at the moment. After that is merged we can automatically install the content from the installation CD.

**Comment by abcdefg30** [comment]
I tried to create a script to extract content from an installed version of ra2. But I couldn't test it yet because I don't have an installation with me atm.
The script is [here](https://github.com/Phrohdoh/oramod-ra2/blob/master/extract%20content.bat). (Just get the latest version of the repo.)

**Comment by abcdefg30** [comment]
> Anyway for extraction from CD(s):
 The actual problem is that the OpenRA content installer is not able to handle the CAB format. (The ra2 mixes are located in  Game1.CAB  on the CD.)
 So we're waiting on OpenRA/OpenRA#8170 at the moment. After that is merged we can automatically install the content from the installation CD.

Seems like I was to fast with this though:
> 17:33 (penev) I decided to try if #8170 can open the RA2 .CAB 
17:33 (penev) guess what 
17:34 (penev) 1178817357 != 0x28635349 
17:34 (+pchote) that means that the ra2 cabs aren't the format that that parser parses

**Comment by DSUK** [comment]
0x4643534d is a microsoft cab file, not an installshield

**Comment by Phrohdoh** [comment]
I plan to begin work on a MSCF parser after lunch.

**Comment by spencer1573** [comment]
I don't know where to put the theme.mix so i can get background. Do i need to rename it as soundtrack or something?  Thanks for the help in advance.

**Comment by Phrohdoh** [comment]
In your content directory for ra2.

OS X: ~/Library/Application Support/OpenRA/Content/ra2/
Linux: ~/.openra/Content/ra2/

**Comment by spencer1573** [comment]
after i made sure it was in that folder for some reason i can't get theme music. bytheway i'm just happy this is a possibility because the original ra2 is so out of date and only works really on old systems.

**Comment by Mailaender** [comment]
Maybe auto-detect the path by reading from the Windows registry so you can rip from Origin.

**Comment by abcdefg30** [comment]
> Maybe auto-detect the path by reading from the Windows registry so you can rip from Origin.

This was added in https://github.com/OpenRA/ra2/pull/246.
